### ISSUE TITLE
Account connection: Cannot create a Jam

### ISSUE THREAD

**Issue by riseandshaheen** [riseandshaheen/jam-twt#4]
**Environment:** Local devnet
**Issue:** On `jam-ui`, there are times when I couldn't submit a Metamask transaction, popup won't open. All show same error as attached below. I got stuck on creation of 3rd Jam. Tried with multiple accounts but the create button gives same error. These requests are not reaching backend.

**Workaround:** Clearing metamask account activity and/or refresh the page BUT this does not work all the time.

```
TypeError: Cannot read properties of undefined (reading 'request')
    at onClick (Create.tsx:165:65)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25)
    at executeDispatch (react-dom.development.js:32128:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7)
    at processDispatchQueue (react-dom.development.js:32173:5)
    at dispatchEventsForPlugins (react-dom.development.js:32184:3)
    at eval (react-dom.development.js:32374:12)
    at batchedUpdates$1 (react-dom.development.js:24953:12)
    at batchedUpdates (react-dom.development.js:28844:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3)
    at dispatchEvent (react-dom.development.js:30141:5)
    at dispatchDiscreteEvent (react-dom.development.js:30112:5)
    ```

**Comment by brunomenezes** [comment]
Fixed on d65e465245926d88a20a77c8fbb01f96788f8539
